# FOLFOX Optimisation Parameters
# All baseline tunable parameters for the optimal FOLFOX scheduler (Simplified Model)

hematology:
  # Hematological parameters
  anc_baseline: 4.5           # Baseline absolute neutrophil count (10^9/L)
  anc_crit: 1.0               # Critical ANC threshold (10^9/L)
  k_out: 0.15                 # Neutrophil turnover rate constant
  k_tox_5fu_dose: 1.0e-5      # Toxicity coefficient per mg of 5-FU dose (PLACEHOLDER)
  k_tox_ox_dose: 5.0e-5       # Toxicity coefficient per mg of Oxaliplatin dose (PLACEHOLDER)
  severe_neutropenia_threshold: 1.0 # ANC threshold for severe neutropenia flag (10^9/L)

neuropathy:
  # Oxaliplatin-induced peripheral neuropathy (Simplified)
  chronic_neuropathy_threshold_mg_m2: 850.0 # Threshold (mg/m2) for chronic neuropathy

dosing:
  # Dosing constraints
  max_daily_5fu_mg_m2: 2400.0   # Maximum daily 5-FU dose (mg/m²)
  max_single_ox_mg_m2: 85.0     # Maximum single oxaliplatin dose (mg/m²)
  min_days_between_ox: 14     # Minimum days between oxaliplatin doses
  patient_weight_kg: 70.0 # Added
  patient_height_cm: 170.0 # Added

utility:
  # Utility (QALY) parameters (Simplified Additive Model)
  baseline_utility: 0.76      # Baseline utility (no side effects)
  neutropenia_penalty: -0.2   # Utility penalty for severe neutropenia
  neuropathy_penalty: -0.24  # Utility loss per step if any neuropathy present

solver:
  # Solver parameters
  tol: 1e-6                   # Solver tolerance
  max_iter: 3000              # Maximum solver iterations
  
optimization:
  # Optimization parameters
  horizon_days: 180           # Treatment horizon (days)
  step_size_days: 1           # Step size for discretization (days)

outputs:
  # Output configuration
  results_dir: results
  save_plots: true # Whether to generate and save plots

# Added Economics section
economics:
  cost_5fu_mg: 0.00442
  cost_ox_mg: 0.10
  cost_infusion_day: 250.0
  cost_pump_day: 12.0
  cost_utility_factor: 0.001 # Adjust this to balance utility vs cost

optimization:
  horizon_days: 180
  step_size_days: 1
